name: Build and Release
on:
  push:
    tags:
      - 'v[1-3]+.[0-9]+.[0-9]+'

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: ./install_dependencies.sh

    - name: Compile Output
      run: ./release.sh

    - name: Add Additional Files
      run: |
        printf "# DATE\n%s\n\n# VERSION\n%s\n", "$(date -u +'%Y-%m-%dT%H:%M:%SZ')", "${{ github.ref }}" >> release/VERSION.md
        cp RELEASE.md release
        cp LICENSE-CC-BY-NC-ND-4.0.md release

    - name: Pack Build Artifacts
      run: tar -cvf release.tar ./release

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: release.tar
        if-no-files-found: error

  Release:
    needs: Build
    runs-on: ubuntu-latest
    steps:

    - name: Download Remote Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: release

    - name: Delete Remote Build Artifact
      uses: geekyeggo/delete-artifact@v5
      with:
        name: release

    - name: Unpack Local Build Artifacts
      run: tar -xvf release.tar

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        draft: false
        prerelease: false
        release_name: The Lord of the Rings - The Motion Picture Trilogy, Screenplay
        tag_name: ${{ github.ref }}
        body_path: release/RELEASE.md

    - name: Upload Release Files
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/pdf/a4/scenes_and_headers/lotr_screenplay_a4_scenes_and_headers.pdf
        asset_name: test.pdf
        asset_content_type: application/pdf
