name: Build and Release
on:
  push:
    tags:
      - 'v[1-3]+.[0-9]+.[0-9]+'

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: ./install_dependencies.sh

    - name: Compile Output
      run: ./release.sh compress

    - name: Pack Build Artifacts
      run: tar -cvf release.tar ./release 

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: release.tar
        if-no-files-found: error

  Release:
    needs: Build
    runs-on: ubuntu-latest
    steps:

    - name: Download Remote Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: release

    - name: Delete Remote Build Artifact
      uses: geekyeggo/delete-artifact@v5
      with:
        name: release

    - name: Unpack Local Build Artifacts
      run: tar -xvf release.tar

    - name: Setup RELEASE.md
        id: setup_release
        shell: bash
        run: |
          r=$(cat release/RELEASE.md)
          r="${r//'%'/'%25'}"
          r="${r//$'\n'/'%0A'}"
          r="${r//$'\r'/'%0D'}"
          echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release/zip/*.zip
        tag: ${{ github.ref }}
        release_name: "The Lord of the Rings - The Motion Picture Trilogy, Screenplay"
        overwrite: true
        file_glob: true
        body: ${{ steps.setup_release.outputs.RELEASE_BODY }}
